Class {
	#name : #FamixFortranUnknownSourceLanguage,
	#superclass : #FamixFortranSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-FortranUDT-Entities-Entities'
}

{ #category : #meta }
FamixFortranUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixFortranSourceLanguage>
	<package: #'Famix-FortranUDT-Entities'>
	<generated>
	^ self
]
