"
Im a special program unit. Im here for distinguish Comment belongs to ProgramUnit and comment not belongs to programUnit. Im a the later one
"
Class {
	#name : #FamixFortran03PUComment,
	#superclass : #FamixFortran03AbstractProgramUnit,
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixFortran03PUComment class >> annotation [

	<FMClass: #PUComment super: #FamixFortran03AbstractProgramUnit>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
