"
I an inheritance association
"
Class {
	#name : #FamixF03Inheritance,
	#superclass : #FamixF03Entity,
	#traits : 'FamixTInheritance',
	#classTraits : 'FamixTInheritance classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixF03Inheritance class >> annotation [

	<FMClass: #Inheritance super: #FamixF03Entity>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
