Class {
	#name : #FamixFortran03SourceTextAnchor,
	#superclass : #FamixFortran03SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixFortran03SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixFortran03SourceAnchor>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
