"
I am a type-bound-procedure in a user-defined-type
"
Class {
	#name : #FamixF03Method,
	#superclass : #FamixF03Entity,
	#traits : 'FamixTMethod',
	#classTraits : 'FamixTMethod classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixF03Method class >> annotation [

	<FMClass: #Method super: #FamixF03Entity>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
