Class {
	#name : #FamixFortran03Model,
	#superclass : #MooseModel,
	#traits : 'FamixFortran03TEntityCreator',
	#classTraits : 'FamixFortran03TEntityCreator classTrait',
	#category : #'Famix-Fortran03-Entities-Model'
}

{ #category : #accessing }
FamixFortran03Model class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
FamixFortran03Model class >> annotation [
	<FMClass: #FamixFortran03Model super: #MooseModel>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
]
