"
I hold the position in the source file
"
Class {
	#name : #FamixFortran03IndexedFileAnchor,
	#superclass : #FamixFortran03SourceAnchor,
	#traits : 'FamixTFileNavigation',
	#classTraits : 'FamixTFileNavigation classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixFortran03IndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixFortran03SourceAnchor>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
