Class {
	#name : #FamixFortran03SourceLanguage,
	#superclass : #FamixFortran03Entity,
	#traits : 'FamixTSourceLanguage',
	#classTraits : 'FamixTSourceLanguage classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixFortran03SourceLanguage class >> annotation [

	<FMClass: #SourceLanguage super: #FamixFortran03Entity>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
