Class {
	#name : #FamixF03UnknownSourceLanguage,
	#superclass : #FamixF03SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixF03UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixF03SourceLanguage>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
