Class {
	#name : #FamixF03SourceTextAnchor,
	#superclass : #FamixF03SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixF03SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixF03SourceAnchor>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
