Class {
	#name : #FamixFortran03UnknownSourceLanguage,
	#superclass : #FamixFortran03SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Fortran03-Entities-Entities'
}

{ #category : #meta }
FamixFortran03UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixFortran03SourceLanguage>
	<package: #'Famix-Fortran03-Entities'>
	<generated>
	^ self
]
