"
a subroutine procedure


"
Class {
	#name : 'FamixF77PUSubroutine',
	#superclass : 'FamixF77PUProcedure',
	#category : 'Famix-Fortran77-Entities-Entities',
	#package : 'Famix-Fortran77-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixF77PUSubroutine class >> annotation [

	<FMClass: #PUSubroutine super: #FamixF77PUProcedure>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
