Class {
	#name : #FamixF77SourceTextAnchor,
	#superclass : #FamixF77SourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixF77SourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixF77SourceAnchor>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
