"
Im an fortran77 instrinsic type.
	- Numeric
	   * Integer
	   * Real
	   * Complex
	- Character
	- Logical
	


"
Class {
	#name : 'FamixF77TypeIntrinsic',
	#superclass : 'FamixF77Type',
	#category : 'Famix-Fortran77-Entities-Entities',
	#package : 'Famix-Fortran77-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixF77TypeIntrinsic class >> annotation [

	<FMClass: #TypeIntrinsic super: #FamixF77Type>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
