Class {
	#name : #FamixF77UnknownSourceLanguage,
	#superclass : #FamixF77SourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixF77UnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixF77SourceLanguage>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
