"
A subroutine (or function) defined in the Fortran language itself


"
Class {
	#name : 'FamixF77IntrinsicRoutine',
	#superclass : 'FamixF77PUProcedure',
	#category : 'Famix-Fortran77-Entities-Entities',
	#package : 'Famix-Fortran77-Entities',
	#tag : 'Entities'
}

{ #category : 'meta' }
FamixF77IntrinsicRoutine class >> annotation [

	<FMClass: #IntrinsicRoutine super: #FamixF77PUProcedure>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
