"
Im an fortran77 instrinsic type.
	- Numeric
	   * Integer
	   * Real
	   * Complex
	- Character
	- Logical
	
"
Class {
	#name : #FamixFortran77TypeIntrinsic,
	#superclass : #FamixFortran77Type,
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixFortran77TypeIntrinsic class >> annotation [

	<FMClass: #TypeIntrinsic super: #FamixFortran77Type>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
