"
a block data for common variable
"
Class {
	#name : #FamixF77PUBlockdata,
	#superclass : #FamixF77ProgramUnit,
	#traits : 'FamixTWithAccesses + FamixTWithLocalVariables + FamixTWithStatements',
	#classTraits : 'FamixTWithAccesses classTrait + FamixTWithLocalVariables classTrait + FamixTWithStatements classTrait',
	#category : #'Famix-Fortran77-Entities-Entities'
}

{ #category : #meta }
FamixF77PUBlockdata class >> annotation [

	<FMClass: #PUBlockdata super: #FamixF77ProgramUnit>
	<package: #'Famix-Fortran77-Entities'>
	<generated>
	^ self
]
